version: "3.7"
services:
  hmo-api:
    container_name: hmo-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3004:3004
    restart: always
    env_file:
      - .env
